services:
- type: web
  name: api
  env: node
  repo: https://github.com/NPNNN/Airbnb_Clone/api
  branch: main
  buildCommand: cd api && yarn install
  startCommand: cd api && yarn start

- type: web
  name: client
  env: node
  repo: https://github.com/NPNNN/Airbnb_Clone/client
  branch: main
  buildCommand: cd client && yarn install && yarn build
  startCommand: cd client && yarn start
